name = "Arbuz Arbuz Pyorni Mod Pack"
author = "YeargLitch&Arbuz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3df7c21cce8b6f3b281a76f923afed7d219ce69a2b97bd9e4df05d194a80554"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
